services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: eon-api
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: eon-client
    ports:
      - "8998:80"
